// AUTO-GENERATED by export_images.py — do not edit by hand.
export type RenderView = { view: string; label: string; src: string };
export type Design = { slug: string; name: string; code: string; stories: number; parti: string; category?: "Residential" | "Mixed-Use"; cover: string; tags: string[]; views: RenderView[] };
export const designs: Design[] = [
  {
    "slug": "costa-verde",
    "name": "Costa Verde",
    "code": "CV-2601",
    "stories": 1,
    "parti": "Flat-roof stucco box with a double-height entry portico and a rear pool \u2014 the clean modern baseline.",
    "cover": "/images/ai-renderings/costa-verde/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/costa-verde/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/costa-verde/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/costa-verde/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/costa-verde/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/costa-verde/corner.jpg"
      }
    ]
  },
  {
    "slug": "verano",
    "name": "Verano",
    "code": "VM-2601",
    "stories": 1,
    "parti": "Low flat-roofed modern home with a deep front porch, circular drive and outdoor BBQ.",
    "cover": "/images/ai-renderings/verano/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/verano/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/verano/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/verano/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/verano/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/verano/corner.jpg"
      }
    ]
  },
  {
    "slug": "mirador",
    "name": "Mirador",
    "code": "MI-2601",
    "stories": 2,
    "parti": "L-shaped split-level: the upper floor cantilevers over the entry, two roof heights, a sunken great room.",
    "cover": "/images/ai-renderings/mirador/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "2-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/mirador/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/mirador/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/mirador/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/mirador/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/mirador/corner.jpg"
      }
    ]
  },
  {
    "slug": "sereno",
    "name": "Sereno",
    "code": "SE-2601",
    "stories": 1,
    "parti": "U-shaped courtyard house wrapping a central pool, glass on three inner faces under a floating teak entry canopy.",
    "cover": "/images/ai-renderings/sereno/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/sereno/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/sereno/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/sereno/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/sereno/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/sereno/corner.jpg"
      }
    ]
  },
  {
    "slug": "ladera",
    "name": "Ladera",
    "code": "LD-2601",
    "stories": 1,
    "parti": "Single-story butterfly roof \u2014 two charcoal shed planes rising to tall outer eaves over full-height glass gable ends.",
    "cover": "/images/ai-renderings/ladera/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/ladera/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/ladera/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/ladera/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/ladera/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/ladera/corner.jpg"
      }
    ]
  },
  {
    "slug": "puente",
    "name": "Puente",
    "code": "PU-2601",
    "stories": 1,
    "parti": "Two floating-roof pavilions joined by a lower glass breezeway you see straight through \u2014 the link is the entry.",
    "cover": "/images/ai-renderings/puente/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/puente/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/puente/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/puente/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/puente/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/puente/corner.jpg"
      }
    ]
  },
  {
    "slug": "solana",
    "name": "Solana",
    "code": "SO-2601",
    "stories": 2,
    "parti": "Two-story board-formed concrete bar with a brise-soleil of vertical teak sun-fins across the upper glass.",
    "cover": "/images/ai-renderings/solana/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "2-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/solana/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/solana/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/solana/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/solana/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/solana/corner.jpg"
      }
    ]
  },
  {
    "slug": "espejo",
    "name": "Espejo",
    "code": "ES-2601",
    "stories": 1,
    "parti": "Miesian glass pavilion floating over a still reflecting pool on slender columns, a travertine bridge to the entry.",
    "cover": "/images/ai-renderings/espejo/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/espejo/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/espejo/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/espejo/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/espejo/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/espejo/corner.jpg"
      }
    ]
  },
  {
    "slug": "terraza",
    "name": "Terraza",
    "code": "TZ-2601",
    "stories": 2,
    "parti": "Three volumes cascading upward, each capped by a planted green roof that becomes a terrace for the tier behind.",
    "cover": "/images/ai-renderings/terraza/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "2-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/terraza/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/terraza/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/terraza/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/terraza/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/terraza/corner.jpg"
      }
    ]
  },
  {
    "slug": "luna",
    "name": "Luna",
    "code": "LU-2601",
    "stories": 1,
    "parti": "A sweeping crescent \u2014 curved white roof and continuous curved glass wrapping a pool held in the arc's embrace.",
    "cover": "/images/ai-renderings/luna/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/luna/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/luna/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/luna/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/luna/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/luna/corner.jpg"
      }
    ]
  },
  {
    "slug": "vela",
    "name": "Vela",
    "code": "VE-2601",
    "stories": 1,
    "parti": "A single dramatic mono-pitch metal roof soaring from a low front eave to a tall glass rear wall, warm cedar sides.",
    "cover": "/images/ai-renderings/vela/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/vela/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/vela/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/vela/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/vela/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/vela/corner.jpg"
      }
    ]
  },
  {
    "slug": "cumbre",
    "name": "Cumbre",
    "code": "CU-2601",
    "stories": 1,
    "parti": "A modern gable in charcoal standing-seam metal with full-height triangular glass gable ends front and rear.",
    "cover": "/images/ai-renderings/cumbre/entry.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/cumbre/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/cumbre/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/cumbre/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/cumbre/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/cumbre/corner.jpg"
      }
    ]
  },
  {
    "slug": "faro",
    "name": "Faro",
    "code": "FA-2601",
    "stories": 1,
    "parti": "A clean flat-roof bar with a raised central glass clerestory 'lantern' running its length over a skylit gallery.",
    "cover": "/images/ai-renderings/faro/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/faro/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/faro/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/faro/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/faro/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/faro/corner.jpg"
      }
    ]
  },
  {
    "slug": "claustro",
    "name": "Claustro",
    "code": "CL-2601",
    "stories": 1,
    "parti": "An enclosed courtyard house \u2014 a solid outer ring wrapping a private glass-lined inner oasis with pool and palms.",
    "cover": "/images/ai-renderings/claustro/aerial.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "1-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/claustro/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/claustro/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/claustro/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/claustro/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/claustro/corner.jpg"
      }
    ]
  },
  {
    "slug": "vuelo",
    "name": "Vuelo",
    "code": "VU-2601",
    "stories": 2,
    "parti": "A sculptural two-story cantilever \u2014 the white upper volume floats over the entry on columns with a teak soffit.",
    "cover": "/images/ai-renderings/vuelo/corner.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "2-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/vuelo/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/vuelo/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/vuelo/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/vuelo/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/vuelo/corner.jpg"
      }
    ]
  },
  {
    "slug": "bayshore",
    "name": "Bayshore",
    "code": "BAY-2601",
    "stories": 2,
    "parti": "The original study that started this series \u2014 a clean modern flat-roof home with a resort-style pool.",
    "cover": "/images/ai-renderings/bayshore/entry.jpg",
    "tags": [
      "Exterior Design",
      "South Florida",
      "2-Story"
    ],
    "views": [
      {
        "view": "entry",
        "label": "Front Entry",
        "src": "/images/ai-renderings/bayshore/entry.jpg"
      },
      {
        "view": "pool",
        "label": "Pool",
        "src": "/images/ai-renderings/bayshore/pool.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/bayshore/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/bayshore/top.jpg"
      },
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/bayshore/corner.jpg"
      }
    ]
  },
  {
    "slug": "podio",
    "name": "Pódio",
    "code": "PDO-2602",
    "stories": 5,
    "parti": "A two-story glass retail podium with a set-back residential bar above, a rooftop amenity terrace and a porte-cochère drop-off.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/podio/corner.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "5-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/podio/corner.jpg"
      },
      {
        "view": "plaza",
        "label": "Plaza Entry",
        "src": "/images/ai-renderings/podio/plaza.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/podio/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/podio/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/podio/street.jpg"
      }
    ]
  },
  {
    "slug": "terrazas",
    "name": "Terrazas",
    "code": "TRZ-2602",
    "stories": 6,
    "parti": "A stepped-setback ziggurat — each tier steps back to open a planted roof-garden terrace cascading with greenery.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/terrazas/aerial.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "6-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/terrazas/corner.jpg"
      },
      {
        "view": "plaza",
        "label": "Plaza Entry",
        "src": "/images/ai-renderings/terrazas/plaza.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/terrazas/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/terrazas/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/terrazas/street.jpg"
      }
    ]
  },
  {
    "slug": "cortina",
    "name": "Cortina",
    "code": "CRT-2602",
    "stories": 6,
    "parti": "An all-glass curtain-wall office slab with an expressed structural grid, fronted by a plaza and a reflecting pool.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/cortina/water.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "6-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/cortina/corner.jpg"
      },
      {
        "view": "water",
        "label": "Reflecting Pool",
        "src": "/images/ai-renderings/cortina/water.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/cortina/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/cortina/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/cortina/street.jpg"
      }
    ]
  },
  {
    "slug": "persiana",
    "name": "Persiana",
    "code": "PRS-2602",
    "stories": 7,
    "parti": "A mixed-use glass block wrapped in a brise-soleil of warm vertical wood-bronze sun-fins tuned to the South Florida sun.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/persiana/fins.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "7-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/persiana/corner.jpg"
      },
      {
        "view": "fins",
        "label": "Sun-Fin Facade",
        "src": "/images/ai-renderings/persiana/fins.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/persiana/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/persiana/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/persiana/street.jpg"
      }
    ]
  },
  {
    "slug": "balcones",
    "name": "Balcones",
    "code": "BLC-2602",
    "stories": 7,
    "parti": "A Miami condo with an offset checkerboard of projecting glass-railed balconies and a rooftop pool deck.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/balcones/facade.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "7-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/balcones/corner.jpg"
      },
      {
        "view": "facade",
        "label": "Balcony Facade",
        "src": "/images/ai-renderings/balcones/facade.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/balcones/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/balcones/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/balcones/street.jpg"
      }
    ]
  },
  {
    "slug": "curva",
    "name": "Curva",
    "code": "CRV-2602",
    "stories": 8,
    "parti": "A bowed, lens-shaped tower of sweeping continuous curved glass, mirrored in a reflecting pool out front.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/curva/water.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "8-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/curva/corner.jpg"
      },
      {
        "view": "water",
        "label": "Reflecting Pool",
        "src": "/images/ai-renderings/curva/water.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/curva/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/curva/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/curva/street.jpg"
      }
    ]
  },
  {
    "slug": "punto",
    "name": "Punto",
    "code": "PNT-2602",
    "stories": 8,
    "parti": "A slender point-tower rising from a two-story podium, addressing a wrapping L-shaped corner plaza.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/punto/corner.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "8-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Corner Hero",
        "src": "/images/ai-renderings/punto/corner.jpg"
      },
      {
        "view": "lookup",
        "label": "Plaza Look-Up",
        "src": "/images/ai-renderings/punto/lookup.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/punto/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/punto/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/punto/street.jpg"
      }
    ]
  },
  {
    "slug": "desplazado",
    "name": "Desplazado",
    "code": "DSP-2602",
    "stories": 9,
    "parti": "Sculptural stacked floor plates shifted alternately left and right, cantilevering over the plaza with exposed terraces.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/desplazado/stagger.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "9-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/desplazado/corner.jpg"
      },
      {
        "view": "stagger",
        "label": "Staggered Massing",
        "src": "/images/ai-renderings/desplazado/stagger.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/desplazado/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/desplazado/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/desplazado/street.jpg"
      }
    ]
  },
  {
    "slug": "verde",
    "name": "Verde",
    "code": "VRD-2602",
    "stories": 9,
    "parti": "A biophilic vertical-garden tower with seven cascading planted sky-terraces wrapping the glass.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/verde/green.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "9-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/verde/corner.jpg"
      },
      {
        "view": "green",
        "label": "Green Facade",
        "src": "/images/ai-renderings/verde/green.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/verde/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/verde/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/verde/street.jpg"
      }
    ]
  },
  {
    "slug": "gemelas",
    "name": "Gemelas",
    "code": "GML-2602",
    "stories": 10,
    "parti": "Twin glass slabs linked by glass-enclosed sky-bridges over a landscaped ground-level courtyard.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/gemelas/bridge.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "10-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/gemelas/corner.jpg"
      },
      {
        "view": "bridge",
        "label": "Sky-Bridge",
        "src": "/images/ai-renderings/gemelas/bridge.jpg"
      },
      {
        "view": "courtyard",
        "label": "Courtyard",
        "src": "/images/ai-renderings/gemelas/courtyard.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/gemelas/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/gemelas/top.jpg"
      }
    ]
  },
  {
    "slug": "giro",
    "name": "Giro",
    "code": "GRO-2602",
    "stories": 10,
    "parti": "A twisting tower — each floor plate rotated a few degrees to spiral roughly 45° up its height.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/giro/twist.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "10-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/giro/corner.jpg"
      },
      {
        "view": "twist",
        "label": "Twist",
        "src": "/images/ai-renderings/giro/twist.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/giro/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/giro/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/giro/street.jpg"
      }
    ]
  },
  {
    "slug": "diagrid",
    "name": "Diagrid",
    "code": "DGR-2602",
    "stories": 11,
    "parti": "An iconic diagrid exoskeleton tower — a triangulated steel net wrapping full-height glass on every face.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/diagrid/facade.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "11-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/diagrid/corner.jpg"
      },
      {
        "view": "facade",
        "label": "Diagrid Facade",
        "src": "/images/ai-renderings/diagrid/facade.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/diagrid/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/diagrid/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/diagrid/street.jpg"
      }
    ]
  },
  {
    "slug": "corona",
    "name": "Corona",
    "code": "CRN-2602",
    "stories": 11,
    "parti": "An office tower crowned by a glowing glass lantern ringed with tapering white blade-fins — a sculptural corona.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/corona/crown.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "11-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/corona/corner.jpg"
      },
      {
        "view": "crown",
        "label": "Crown",
        "src": "/images/ai-renderings/corona/crown.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/corona/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/corona/top.jpg"
      },
      {
        "view": "street",
        "label": "Street View",
        "src": "/images/ai-renderings/corona/street.jpg"
      }
    ]
  },
  {
    "slug": "voladizo",
    "name": "Voladizo",
    "code": "VLD-2602",
    "stories": 12,
    "parti": "A bold cantilever — the upper volume oversails the plaza over a double-height sky-lobby, with a rooftop pavilion.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/voladizo/plaza.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "12-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/voladizo/corner.jpg"
      },
      {
        "view": "plaza",
        "label": "Plaza",
        "src": "/images/ai-renderings/voladizo/plaza.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/voladizo/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/voladizo/top.jpg"
      }
    ]
  },
  {
    "slug": "faro-alto",
    "name": "Faro Alto",
    "code": "FAR-2602",
    "stories": 12,
    "parti": "The finale — a slender beacon tower topped by a lit glass lantern crown and mast, mirrored in a reflecting pool at dusk.",
    "category": "Mixed-Use",
    "cover": "/images/ai-renderings/faro-alto/night.jpg",
    "tags": [
      "Mixed-Use",
      "South Florida",
      "12-Story"
    ],
    "views": [
      {
        "view": "corner",
        "label": "Street Corner",
        "src": "/images/ai-renderings/faro-alto/corner.jpg"
      },
      {
        "view": "beacon",
        "label": "Beacon",
        "src": "/images/ai-renderings/faro-alto/beacon.jpg"
      },
      {
        "view": "night",
        "label": "Plaza at Night",
        "src": "/images/ai-renderings/faro-alto/night.jpg"
      },
      {
        "view": "aerial",
        "label": "Aerial",
        "src": "/images/ai-renderings/faro-alto/aerial.jpg"
      },
      {
        "view": "top",
        "label": "Top View",
        "src": "/images/ai-renderings/faro-alto/top.jpg"
      }
    ]
  }
];
